name = "office-user-auto-create"
account_id = ''
type = 'webpack'
workers_dev = true
webpack_config = 'webpack.config.js'

[vars]
_ANNOUNCEMENT = "some announcement"
_GET_CODE_LINK = "1"
_AAD_CONFIG = "{ \"tenantId\": \"281f8245-c210-4396-bfa2-caada3279bad\", \"clientId\": \"b0c30093-45c5-46b9-8d20-76b47329a74a\", \"clientSecret\": \"aS18Q~hb303mu6pt7SlnwtoR0_dLoGDTDbd2Hcwu\" }"
_OFFICE_DOMAINS = "[\"kkljj.onmicrosoft.com\", \".omicrosoft.com\"]"
_OFFICE_SUBSCRIPTIONS = "[{ \"name\": \"Office 365 E1\", \"sku\": \"Office 365 E1\" }, { \"name\": \"subscription 2\", \"sku\": \"skuid\" }]"
_USERNAME_BLACKLIST = "[\"admin\", \"gay\"]"
_GENERATE_CODES_PATH_SECRET = "/070900"
